######################################################################
# Automatically generated by qmake (2.01a) qua jun 2 09:51:16 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += atoms.hpp border.hpp frame.hpp header.hpp x11management.hpp debug.hpp
SOURCES += atoms.cpp border.cpp frame.cpp header.cpp main.cpp x11management.cpp debug.cpp
