######################################################################
# Automatically generated by qmake (2.01a) qua jun 2 09:51:16 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += atoms.hpp windowmanager.hpp debug.hpp client.hpp decoratedframe.hpp
SOURCES += atoms.cpp main.cpp windowmanager.cpp debug.cpp client.cpp decoratedframe.cpp
